### PR TITLE
Fix for wijmo separator not being centered.

### PR DESCRIPTION
**Pull request by Francisc**
Minor edit for horizontal wijmo separator.

### CODE REVIEW

**Comment by addyosmani** [comment]
@Francisc This fix looks good in Chrome. Have you had a chance to test in other browsers?

**Comment by Francisc** [comment]
I thought I did, but it seems there are a few issues in Opera and Safari.
From what I could see it's to do with single pixel division. (1% margin is x.5 px, where x is an integer)
So, there's a few options:
1. Set separator width to 100%. No left and right spacing from edge.
2. Set separator width to 96% and left and right margins to 2%. I tested this and it works on IE8+, Chrome, Safari, Firefox and Opera 11.60.
3. Set separator width in px. I've seen that the containing `<ul>` element is set to 160. Problem here is that if the width of the `<ul>` is changed, the separator will look bad.
4. Use pseudo-elements in the `<li>` separator. This won't work on non-supporting browsers.
5. Place a span or div element inside the separator `<li>` which an be centered relative to the `<li>`. Problem with this is the fact that we add extra markup for presentational purposes.

**Comment by addyosmani** [comment]
@Francisc Thanks for testing and the options. So, if I'm correct, option 2 is probably the one to go for?

**Comment by Francisc** [comment]
Yeah, 1 or 2 are the best ones. It's up to visual taste. OK, so 96% and 2% margin.

**Comment by addyosmani** [comment]
Would you like to submit another PR with the fix? :)

**Comment by Francisc** [comment]
Sorry, was out having lunch. Sure, coming right up.

**Pull request merged**
