### PR TITLE
Changed the dropdown hover colour to match the hover effects of the tabs...

### PR DESCRIPTION
**Pull request by BenHall**
.... Having it as blue looked a little inconsistent.  This might be a personal choice.

### CODE REVIEW

**Comment by addyosmani** [comment]
@BenHall Thanks. I'm going to leave this one open for people to vote on. I personally liked the blue hover colors but I see what you're saying about hover states on tabs and dropdowns being consistent. 

Anyone else have preferences?

**Comment by vierbergenlars** [comment]
@addyosmani Consistency is better, i think

**Comment by BenHall** [comment]
With Twitter V2, it looks like the approach you took may be the default. Something to think about.

**Comment by addyosmani** [comment]
@BenHall Thanks. I think we'll be reviewing all of the hover, active etc states in detail as a part of #52

**Comment by addyosmani** [comment]
This will be addressed as a part of the rewrite for bootstrap 2.0

**Pull request closed without merging**
