### PR TITLE
jQuery UI custom input fields

### PR DESCRIPTION
**Pull request by panosru**
I added the support for custom input fields with the look and feel of Twitter bootstrap. I used filament's jquery plugin and I improved it a little bit in order to fit the needs.

You can check the input file here: http://panosru.github.com/jquery-ui-bootstrap

You can customize it on how ever you like, the main properties are the followings: 
1. **button_position** (default value is _right_ it accepts _right_ or _left_ as values)
2. **extra_class** (default value is _span3_ it accepts classes, mostly used to set the width of the element but you can hook more classes by separating them with space)
3. **feedback_text** (default value is _No file selected..._)
4. **button_text** (default value is _Browse_)
5. **button_change_text** (default value is _Change_)

You can have your input file html like this: `<input type="file" name="file" id="file" />`

and your js code like this: `$('#file').customFileInput();`

The interesting part is the _button_text_ and _button_change_text_ properties where you can set your html code (for example an image tag and you then will have an image instead of text button

for example the following: 

```
$('#file').customFileInput({
    button_text : '<img src="/img/arrow-up.png">'
});
```

will produce something like this: image button

### CODE REVIEW

**Comment by addyosmani** [comment]
@panosru this is excellent work! Thanks. I probably won't get to review it until tomorrow but I'll let you know if there is anything that needs to be changed then :)

How's browser support looking?

**Comment by panosru** [comment]
Tested on latest versions of Safari, Chrome, Opera, Firefox also tested in Chrome Canary, Opera Next and Firefox 10 beta.

Didn't test it on IE at all because I'm too lazy to run bootcamp or start vm in order to boot into windows and test IE but I believe it will work on IE I didn't applied any kind of hacks I followed "standards" so it should work at least on IE9 for sure but I believe IE8/7 should be ok too... 

If you are on Windows you could run the demo page http://panosru.github.com/jquery-ui-bootstrap and check it out :)

**Comment by panosru** [comment]
I did a check on windows, it seems that IE8 and IE7 are not compatible because you can't fire an event from element A to element B, IE9 and IE10 works fine (so personally I don't care for IE8/7) but I will check it out a bit to see if I can find a work-around.

Another minor issue is that the button is 1px higher in y axis on IE8/7

EDIT:
I'm not really sure if it is IETester's issue or no but when I run IE9 and I start developer tools and then I set _Browser Mode: IE8 / Document Mode: IE8 Standards_ everything seems to work (but without rounded corners) when I set _Browser Mode: IE7 / Document Mode: IE7 Standards_ The button is 1px down on y axis (I mentioned wrong before that it was 1px up) but file browsing works fine.

I will do a pull request for these changes

**Comment by panosru** [comment]
I believe now that it should be ok but I'm not 100% sure since with IETester file browsing wasn't working with IE9 running as IE7 & IE8 mode file browsing was working... so I will wait someone to go [here](http://panosru.github.com/jquery-ui-bootstrap/) and check if it is working or no :)

**Comment by panosru** [comment]
Also forgot to mention, I moved less files under bootstrap folder since they belong there so remove them from css folder.

**Comment by LKay** [comment]
Three things to fix from me. :)
1. Config to customFileInput() should be more  jQuery way:
   
   ```
   $.fn.customFileInput = function(options){
     var settings = jQuery.extend({
       'button_position' : 'right',
       'extra_class' : 'span3',
       'feedback_text' : 'No file selected...',
       'button_text' : 'Browse',
       'button_change_text' : 'Change'
     }, options);
   
   ...
   }
   ```
   
   So now you should use `settings` variable for config properties.
2. Plugin should take classes already set for file input and not overwrite them ie. `<input type="file" class="span5">` should preserve `span5` class after fileCustomInput() call.
3. Some minor fixes should be done for Android browser (don't know what it is look like in iOS browser). The button to browse is fine, but field for selected file name looks like height of the element isn't set so it is displayed a little weird.

I can make 2 first fixes when pull request is accepted.

**Comment by addyosmani** [comment]
@panosru Thanks once again for all of your work on this. I think we need to decide whether we want to actually supply a 'patched' version of the plugin FilamentGroup released (based on the feedback from above) or just focus on getting the theme here working. @LKay what are your thoughts on this? I agree that we should be aiming for best practices but as much as possible, I don't want us to become a support-point for plugins (we just want to support them thematically).

What I think I'll do this weekend is go through the code @panosru has been working on and see if there are any stylistic differences that could be updated. If not, I'll wrap up the IE fixes and make sure everything is working. Cheers!

**Comment by panosru** [comment]
@LKay 
Thanks for mentioning those, personally I have no plans to support this in mobile devices I believe if you plan to build a web application you need to create another layout for mobile and there are lot's of powerful libraries supporting mobile, including jQuery Mobile since we talking about jQuery (but there are others too equally good and maybe better too). Regarding the 1st two notices I implemented them, check the code and if you have to suggest any correction feel free to do so or pull the requests in my fork :)

@addyosmani 
unfortunately with CSS only you won't be able to archive the same look and feel, besides the script is quite simple and we are talking open source here so I believe that there is no need to be afraid of supporting 3rd party plugins. Besides it is working as it is now so no need for changes except if a browser update will break functionality or of html specs will change :P In the bottom line I think it's not a big trouble to extend 3rd party plugins and provide something better :)

**Comment by addyosmani** [comment]
@panosru sounds great! I reviewed the current version you have on GH pages (originally linked in the issue) and it looks good. I'm going to make some stylistic updates to just make it fall in line with some of the other buttons but it'll definitely land this weekend.

I'm actually in agreement regarding mobile support. 50% of the companies I've seen using jQUI components actually end up creating mobile extensions specific to non-desktop devices and imo, whilst a valid concern, this is beyond the scope of this project.

**Comment by addyosmani** [comment]
I've made my changes to the PR and cross-browser tested. Happy with the current state of it, so the next change will be this issue getting fixed/closed. Thanks for your help with this @panosru!.

**Comment by panosru** [comment]
@addyosmani I like the way you styled the button! :D 

just a silly question since I'm not github expert (yet) what should I do with my fork repository? I can remove it now and re-fork your's when I need to pull request again? :D

**Comment by addyosmani** [comment]
@panosru Thanks! :) So, there are two options with what you could do with your fork. You could either grab the latest version of this project, manually make your changes to it and then push that to your fork, or get rid of the fork completely and re-fork. I would personally opt for the first of those :)

I've added the changelog for the release including this change here https://github.com/addyosmani/jquery-ui-bootstrap/wiki/0.23 and I'll be sure to mention you in the updated release post next week!

**Comment by panosru** [comment]
Hello, thanks for your reply and sorry for trolling the issue here, I would love to know why you prefer first option since second is much easier :D

**Comment by addyosmani** [comment]
@panosru Not at all. So, the second option is easier but has bit me in the past with renames to forks (so, deleting a fork of something called 'project' and re-forking ended up creating 'project-1'. The references to the source/master project don't actually change so it's not that big a deal, but again just personal preference. Use whichever you feel the most comfortable with!. Looking forward to seeing how plupload support comes along!

**Comment by panosru** [comment]
@addyosmani Thanks a lot! :) I will go for the 1st one then :) plupload is still underway but I hope I'll find some more time for it :)

**Pull request closed without merging**
