### PR TITLE
Fixing issue #1: Fix accordion jumpiness issues

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by addyosmani** [comment]
@eliperelman this certainly seems to be an improvement over what we had before. In Chrome I'm currently still seeing a little bit of a jump during switching (probably a 1px jump). Are you experiencing this at all or are you using a different browser?

Thanks again!

**Comment by eliperelman** [comment]
I was just typing that up as you wrote that!

What I was saying was that this also happens on the default jQuery UI accordion on their demo site, so this would appear to be an issue in the jQuery UI code:

http://jqueryui.com/demos/accordion/

**Comment by eliperelman** [comment]
And I noticed this issue in Chrome 16. Firefox 8 seems fine.

**Comment by addyosmani** [comment]
Aha!. You are indeed correct. I'm wondering if we should attempt to fix this or leave as-is if other jQuery UI themes are doing the same. What do you think?

**Comment by eliperelman** [comment]
I was considering that as well, but most likely this is an issue with the jQuery UI JS, and changing that would make the custom JS unable to upgrade. Probably better to file an issue with jQuery UI and eventually benefit from the fix. What do you think?

**Comment by addyosmani** [comment]
@eliperelman I agree completely. I have a feeling that given we both noticed the issue it's possible this is something they're already taking care of with 1.9, but I'll go ahead and merge the changes made. Thanks so much once again!

**Comment by eliperelman** [comment]
No, problem, glad to help.

**Pull request merged**
