### PR TITLE
reflect Bootstrap's branding change

### PR DESCRIPTION
**Pull request by cvrebert**
See http://getbootstrap.com/about/#brand
It's now simply "Bootstrap" rather than "Twitter Bootstrap".

### CODE REVIEW

**Comment by cvrebert** [comment]
@gtraxx Ping.

**Comment by cvrebert** [comment]
@gtraxx Ping on this.

**Comment by cvrebert** [comment]
@gtraxx **Pingity pingity ping!**

**Comment by gtraxx** [comment]
Thanks for contribution :)

**Pull request merged**
