### PR TITLE
Wijmo minor fixes to top border radius and dropdown item padding

### PR DESCRIPTION
**Pull request by Francisc**
Worked on issue here: https://github.com/addyosmani/jquery-ui-bootstrap/issues/12
- Removed Wijmo top-left and top-right border radius
- Fixed padding issue

### CODE REVIEW

**Comment by addyosmani** [comment]
@Francisc Thanks! I'll review this tonight and merge assuming everything looks good.

**Comment by Francisc** [comment]
OK. I hope I understood what you wanted and that the placement is correct (bootstrap.css).
Thanks.

**Comment by addyosmani** [comment]
Addressing this in #26. Thanks for your input!

**Comment by Francisc** [comment]
Thank you as well.

**Pull request closed without merging**
