### PR TITLE
CSS Change between 1.9.0 and 1.9.1

### PR DESCRIPTION
**Pull request by benjamin-bd**
I have apply the css change that are related to jqueryui 1.9.0  to 1.9.1, (you need to have the 1.9.1 js)

Unfortunately I haven't test it through out

### CODE REVIEW

**Comment by addyosmani** [comment]
@gtraxx what do you think?

**Comment by gtraxx** [comment]
Hi Addy, I will test the changes :)

**Comment by gtraxx** [comment]
i'm valid modification but I'll work on the other :)

**Comment by addyosmani** [comment]
great. thanks!

**Comment by benjamin-bd** [comment]
thanks a lot / merci beaucoup Gtraxx

**Comment by gtraxx** [comment]
@benjamin-bd  Pas de problème, plus facile d'avancer à plusieurs :)
@addyosmani :)

**Pull request merged**
