### PR TITLE
LESS Support - Part 3

### PR DESCRIPTION
**Pull request by dharapvj**
Added support for rest of the components from components.html page.

Now remaining are components on extra.html and map.html.

### CODE REVIEW

**Comment by gtraxx** [comment]
Hi @dharapvj , There is a conflict with merge ?
@addyosmani

**Comment by dharapvj** [comment]
I also saw that github saying that it could not auto merge..  but I have taken everything latest etc before making the pull request.  Will review once more in my morning and will update you.. 

Sorry for the inconvenience :-(

**Comment by dharapvj** [comment]
I think I have figured out the issue. I will try to patch this pull request today.

**Comment by dharapvj** [comment]
Hi @gtraxx,

Could you try again? Hope now this should go through. 

Let me know if this does not work. In that case I will close this request and open a fresh request.

**Comment by gtraxx** [comment]
Thanks @dharapvj  :D

**Comment by dharapvj** [comment]
@gtraxx : My pleasure.

BTW.. with this, my LESS work is all caught up with your changes in CSS side. So if that was a showstopper from making the masterbs3 branch the default, we are good to go ahead. 

There are few color hard-codings as of now, which I am planning to move to additional variable definitions. But at least beta version can be published now.

I do have some nitpicking about the current CSS behavior which I want to wish to take some screenshots and open as a single consolidated issue for your review. e.g. In extra tab, Wijmo header does not look good etc. I will report it in coming days. The corresponding fixes, if any in CSS side, will need to be moved in LESS code later on again.

**Pull request merged**
