### PR TITLE
Send version 0.5 and new documentation

### PR DESCRIPTION
**Pull request by gtraxx**
### New Layout

New layout of documentation and added information on the use of jQuery UI Bootstrap.
### New documentation with demo
- Home page (index.html)
- Extra page (extra.html)
### Technical changes
- Upgrade jQuery UI 1.10.0
- Upgrade jQuery 1.9.0
- Upgrade bootstrap + Choose components Twitter Bootstrap for jQuery UI
- Adding Font Awesome in doc

View Commit info :)

### CODE REVIEW

**Comment by gtraxx** [comment]
Hi @addyosmani ,
Can I merge ?
You can replace the current doc: http://addyosmani.github.com/jquery-ui-bootstrap with the new ?
;)

**Comment by addyosmani** [comment]
And...merged! :)

**Comment by addyosmani** [comment]
Fantastic work on this. I'm catching up with email but just wanted to say what a wonderful job you had done with these updates. Question: would it make sense for us to drop the addyosmani.github.com hosted version of the site and just create a gh-pages branch here which we then point as the default branch for master? We've done that for other projects like TodoMVC and its worked well but just wanted to check.

**Comment by gtraxx** [comment]
Yes you can.
Users can use the new documentation that contains a lot of information to help them. :)

**Comment by addyosmani** [comment]
Okay. I just did re-arranged all the branches and we should now have:
- gh-pages _is_ our new master. We push here directly and make pull requests against this branch
- http://addyosmani.github.com/jquery-ui-bootstrap/ :)

**Comment by gtraxx** [comment]
Great :D

**Comment by gtraxx** [comment]
Hello @addyosmani , 
if I make changes should I push gh-pages and master ?
Or only to gh-pages ?
:)

**Comment by addyosmani** [comment]
gh-pages all the way :) We're going to kill off master once we no longer
need it.

**Comment by gtraxx** [comment]
okay, I send fix bug :)

**Pull request merged**
