### PR TITLE
Fixed some of the obvious problems in the demo

### PR DESCRIPTION
**Pull request by ghost**
included bootstrap 2. 
Fixed img-path. 
Fixed layout. 
Fixed navbar. 
Added missing variables. 
New JQuery An JQueryUI versions.

### CODE REVIEW

**Comment by chrisirhc** [comment]
You might not have set your email correctly in git. Refer to: https://help.github.com/articles/setting-your-email-in-git
After setting your email, remember to look under 'my commits weren't changed' and do a force push into the same branch that was the source of this pull request to update these commits.

**Comment by gtraxx** [comment]
Sorry but work has already been done in the master
Please check the master before making changes

This change is not valid, I've applied all changes a week ago in the master !!!!!

**Comment by ghost** [comment]
@gtraxx This pull request is 4 months old, so please relax :)

**Comment by gtraxx** [comment]
@maklemenz no problem :)

**Comment by addyosmani** [comment]
@gtraxx Should we close this? (thanks so much once again for your initial work on this @maklemenz!)

**Comment by gtraxx** [comment]
@addyosmani I checked and changes are made following changes in bootstrap 2.2.1 and jQuery UI 1.9.x
But it's a good job @maklemenz

**Comment by ghost** [comment]
closed

**Pull request closed without merging**
