### PR TITLE
Implemented Wijmo Menu Support

### PR DESCRIPTION
**Pull request by banzor**
Did a rewrite of Wijmo Menu support for the theme.
Main work done:
- Removed wijmenu JS and CSS
- Added wijmo-open combined/minified JS and CSS
- Added wijmenu CSS overrides needed to main theme CSS file
- Changed behavior of wijmenu to be open-on-click
- Removed unnecessary custom click and hover code added to wijmenu elements

### CODE REVIEW

**Comment by banzor** [comment]
Once this is merged I will re-fork and add Wijmo Tooltip support

**Comment by addyosmani** [comment]
Thanks for the PR @banzor! I'll review this in more depth tomorrow and ping if there's anything that might need a little more work. Fingers crossed it'll be good for a merge :)

**Comment by banzor** [comment]
Yeah, let me know Addy. I will be happy to make any edits you need.

**Comment by addyosmani** [comment]
@banzor Just reviewed in a few different browsers. It's almost perrfect :) 

The only one change I'd make is perhaps adjusting `.wijmo-wijmenu h3 a` to margin-top:2px or 1px as 'Project Name' it seems a little off the vertical middle at the moment. It's only minor.

It looks as though this set of changes can't be manually merged but I can take a look at sorting out the changes this weekend and I should be able to get this in for version 0.14 (which I'll push next week).

Thanks again.

**Comment by banzor** [comment]
@addyosmani Would it help if I document the changes? I could send you a list of what to do to incorporate my changes. 

Or if it would help for me to re-fork and apply changes to the latest version I could do that. 

Just let me know.

**Comment by addyosmani** [comment]
@banzor Either would be great. Whatever you have time for would be appreciated :)

**Comment by addyosmani** [comment]
@banzor I've manually merged in your changes. One or two minor fixes were made to resolve conflicts between recent changes and styles, but I believe everything should be working nicely now. Thanks again for the work on this.

Before I push the current version in the repo to the live site, could you take a look at the menu to make sure you're happy with whats there at the moment? LGTM atm. Cheers!

**Comment by banzor** [comment]
@addyosmani Just checked the merge. Everything looks good to go! I will re-fork from this and start adding more wijmo support.

**Comment by addyosmani** [comment]
Perfect @banzor! Thanks :) I'll close this issue and push these changes to the live site later in the week. Cheers!

**Pull request closed without merging**
