### PR TITLE
Remove older jQuery library, optimise images

### PR DESCRIPTION
**Pull request by philwareham**
I've left the jQuery UI 1.9.2 CSS files in place for now, but I guess they could be removed too?

### CODE REVIEW

**Comment by gtraxx** [comment]
Ok we add tags to save old files

**Comment by gtraxx** [comment]
@philwareham 
Are you interested in working on LESS or SASS version ?
Thanks for contribution :)

**Comment by philwareham** [comment]
I use Sass day-to-day but I have used Less before too. Prefer Sass to be honest.

**Comment by gtraxx** [comment]
Is what you would like to create SASS version ?
I can do LESS version but you could handle version SASS ?
Thank you for helping to clean files :+1:

**Comment by philwareham** [comment]
I can, but wouldn't it be better to just choose one syntax? In this case I guess LESS would be the logical choice since that's what Bootstrap uses.

**Comment by gtraxx** [comment]
yes I agree, but can be checked priorities.
@addyosmani you prefer to start on SASS or LESS, or SASS and LESS :)

**Comment by addyosmani** [comment]
I think we should opt for just one and roll with it. My personal preference would be that we ran with SASS, but I want to make sure everyone is happy with that :)

**Comment by philwareham** [comment]
I'm happy with that, since I prefer using Sass.

**Pull request merged**
