### PR TITLE
CSS code cleanup for easier development

### PR DESCRIPTION
**Pull request by philwareham**

### CODE REVIEW

**Comment by gtraxx** [comment]
At what time did you do the cleaning ?
I have to do a manual merge, Did you use my edits 24/01/2012 (https://github.com/addyosmani/jquery-ui-bootstrap/commit/7798159130210f31c97e0ee4b86192ddc3ddc3f6) ?
Thanks :)

**Comment by philwareham** [comment]
I forked from master, earlier today.

**Comment by gtraxx** [comment]
The new master is gh-pages :(
@addyosmani you have a solution ? :)

Thanks @philwareham

**Comment by philwareham** [comment]
If the gh-pages was only recently branched, I can cancel my pull request and check against commits made specifically to gh-pages - then I can do a new pull request to that branch instead?

**Comment by philwareham** [comment]
Actually I've compared my code against the CSS file in gh-pages and they contain the same changes, so it would be safe to merge this pull request into the gh-pages branch as is.

**Comment by addyosmani** [comment]
@philwareham First, thanks for putting this together. Would you mind sending through a new pull request against gh-pages?

@gtraxx Maybe we should update our readme to say which branch changes should be made against.

**Comment by philwareham** [comment]
I think it already _is_ a pull request to gh-pages? Let me know if not.

I've got a fair few other changes I could provide going forward.

**Comment by addyosmani** [comment]
Ah, so it is. It looks like we might actually have some merge conflicts as we can't automatically merge these changes. If you have a chance, could you rebase?

**Comment by gtraxx** [comment]
@philwareham Must make the changes from the file folder gh-pages to avoid conflicts.
@addyosmani 
yes make a changelog (changelog.txt)
Do you want me to do ?

**Comment by addyosmani** [comment]
@gtraxx A changelog would be great. I was actually thinking of maybe expanding readme with a contributors section that mentions our PR process (i.e submit against gh-pages etc).

**Comment by philwareham** [comment]
Ok I'll rebase and resend later today. Cheers.

**Comment by gtraxx** [comment]
Hi philwareham,
thank you :)

**Pull request closed without merging**
